### ISSUE TITLE
Password is not updated correctly if it contains a #

### ISSUE THREAD

**Issue by dops-at** [rabbitmq/default-user-credential-updater#42]
I had a problem last night where the rabbitmq admin password has been rotated in vault and the change was picked up by the [default-user-credential-updater](https://github.com/rabbitmq/default-user-credential-updater).
The password contains a # and everything behind this character was striped!
The password should be e.g. **!jkwhe4FAD$^ke#j34SD34kk3pokj$43** but it was **!jkwhe4FAD$^ke**

By setting the same password in rabbitmq itself via UI it works as expected!

**Comment by MirahImage** [comment]
Hi, I've added a test [on a branch](https://github.com/rabbitmq/default-user-credential-updater/tree/test-hash-in-password) to check if it correctly interprets an INI file with a `#` character in the password, and assuming the `#` character is written into the config file, then the credential updated does update the password successfully. 

We will continue to look into this. Right now my suspicion is that this may actually be a bug in the vault agent, but this requires further investigation.

**Comment by ChunyiLyu** [comment]
Hi @dops-at, for cluster operator deployed RMQ, we use [RMQ configuration files](https://www.rabbitmq.com/configure.html#config-file) to set its default user credentials. RMQ conf files follow sysctl configuration file format and treat `#` as start of a comment. One workaround is to set a rabbitmq password policy in Vault to exclude `#` from vault password generation: https://developer.hashicorp.com/vault/docs/concepts/password-policies
